version: '3.8'

networks:
  k6:
  grafana:
  timescaledb:

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    command: postgres -c shared_preload_libraries=timescaledb
    networks:
      - k6
      - grafana
      - timescaledb
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/timescaledb
      - POSTGRES_DB=k6
      - POSTGRES_USER=k6
      - POSTGRES_PASSWORD=k6

  grafana:
    image: grafana/grafana
    networks:
      - grafana
      - timescaledb
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
